import Foundation
import GossveilKit

public enum GossveilError: Error, Sendable {
    case invalidState(String)
    case internalError(String)
    case nullParameter(String)
    case invalidArgument(String)
    case invalidType(String)
    case invalidUtf8String(String)
    case protobufError(String)
    case legacyCiphertextVersion(String)
    case unknownCiphertextVersion(String)
    case unrecognizedMessageVersion(String)
    case invalidMessage(String)
    case invalidKey(String)
    case invalidSignature(String)
    case fingerprintVersionMismatch(theirs: UInt32, ours: UInt32)
    case fingerprintParsingError(String)
    case sealedSenderSelfSend(String)
    case untrustedIdentity(String)
    case invalidKeyIdentifier(String)
    case sessionNotFound(String)
    case invalidSession(String)
    case invalidRegistrationId(address: ProtocolAddress, message: String)
    case invalidProtocolAddress(name: String, deviceId: UInt32, message: String)
    case invalidSenderKeySession(distributionId: UUID, message: String)
    case duplicatedMessage(String)
    case verificationFailed(String)
    case nicknameCannotBeEmpty(String)
    case nicknameCannotStartWithDigit(String)
    case missingSeparator(String)
    case badDiscriminatorCharacter(String)
    case badNicknameCharacter(String)
    case nicknameTooShort(String)
    case nicknameTooLong(String)
    case usernameLinkInvalidEntropyDataLength(String)
    case usernameLinkInvalid(String)
    case usernameDiscriminatorCannotBeEmpty(String)
    case usernameDiscriminatorCannotBeZero(String)
    case usernameDiscriminatorCannotBeSingleDigit(String)
    case usernameDiscriminatorCannotHaveLeadingZeros(String)
    case usernameDiscriminatorTooLarge(String)
    case unknown(UInt32, String)

    /// The error a core status stands for, with the core's own words.
    static func of(status: Int32) -> GossveilError {
        let message = String(cString: gv_status_text(status))
        switch GvStatus(rawValue: UInt32(status)) {
        case GV_BAD_ARGUMENT: return .invalidArgument(message)
        case GV_BAD_STATE: return .invalidState(message)
        case GV_BAD_KEY: return .invalidKey(message)
        case GV_BAD_SIGNATURE: return .invalidSignature(message)
        case GV_BAD_MESSAGE: return .invalidMessage(message)
        case GV_UNKNOWN_KEY_ID: return .invalidKeyIdentifier(message)
        case GV_UNTRUSTED_IDENTITY: return .untrustedIdentity(message)
        case GV_NO_SESSION: return .sessionNotFound(message)
        case GV_REPLAY: return .duplicatedMessage(message)
        case GV_LEGACY_VERSION: return .legacyCiphertextVersion(message)
        case GV_UNKNOWN_VERSION: return .unrecognizedMessageVersion(message)
        case GV_VERIFY_FAILED: return .verificationFailed(message)
        default: return .internalError(message)
        }
    }
}
